name: mobile_app_pocketpartners
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.2.3
  http: ^1.4.0
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  cloudinary_url_gen: ^1.0.0
  cloudinary_api: ^1.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
